add bilanzierungs objects
bo4e/BO4E-python pull request #508
Opened 2023-08-14 08:07 UTC by hf-ddernbach

2023-08-21 07:43 UTC, FreddyFox892 commented on src/bo4e/bo/bilanzierung.py
> +kundenwert: Optional[Menge] = None
Kommentar

2023-08-23 12:24 UTC, hf-ddernbach commented on src/bo4e/bo/bilanzierung.py
> +    # _marktlokations_id_check = field_validator("marktlokations_id")(validate_marktlokations_id)
98d36927a9bd78d6028e55200dd864f0488be29a

2023-08-23 12:31 UTC, hf-ddernbach commented on src/bo4e/bo/bilanzierung.py
> +    # optional attributes
1ccf38184b1ab1a24d96354368fcfa3b1e7638a5

2023-08-23 12:32 UTC, hf-ddernbach commented on src/bo4e/com/lastprofil.py
> +    """
56cb779c6f4e28e79cd7458de1c48fc8c2fc5636

2023-08-23 12:33 UTC, hf-ddernbach commented on src/bo4e/enum/botyp.py
> +    # work in progress
2d7432df71c0a93f0e58683ba4693c2ef2af54cd

2023-08-23 12:33 UTC, hf-ddernbach commented on src/bo4e/enum/profilart.py
> +Contains class Profilart
1bd5c00699b36bcc3492a0a26a5eb0bd49a92070

2023-08-23 12:33 UTC, hf-ddernbach commented on src/bo4e/enum/profiltyp.py
> +Contains class Profiltyp
1bd5c00699b36bcc3492a0a26a5eb0bd49a92070

2023-08-23 12:33 UTC, hf-ddernbach commented on src/bo4e/enum/wahlrechtprognosegrundlage.py
> +Contains class Wahlrechtsprognosgrundlage
1bd5c00699b36bcc3492a0a26a5eb0bd49a92070

2023-08-23 12:34 UTC, hf-ddernbach commented on src/bo4e/enum/zeitreihentyp.py
> +Contains class Zeitreihentyp
1bd5c00699b36bcc3492a0a26a5eb0bd49a92070

2023-08-23 14:02 UTC, lord-haffi commented on tests/test_bilanzierung.py
> +            _instantiate_malo(malo_id_valid[0])
```suggestion
        "malo_id,is_valid",
        [
            pytest.param("51238696781", True),
            pytest.param("41373559241", True),
            pytest.param("56789012345", True),
            pytest.param("52935155442", True),
            pytest.param("12345678910", False, id="wrong checksum"),
            pytest.param("529351554422", False, id="too long"),
            pytest.param("5293515544", False, id=""too short"),
            pytest.param("5293v15a442", False, id="alphanumeric"),
            pytest.param("asdasd", False),
            pytest.param("   ", False),
            pytest.param("  asdasdasd ", False),
            pytest.param(None, True, id="malo_id not required"),
            pytest.param("", False),
        ],
    )
    def test_id_validation(self, malo_id: str, is_valid: bool) -> None:
        """
        Test different MaLos.
        Field optional -> None values are allowed
        """

        if not is_valid:
            with pytest.raises(ValidationError):
                _ = Bilanzierung(marktlokations_id=malo_id)
        else:
            _ = Bilanzierung(marktlokations_id=malo_id)
```

2023-08-23 14:07 UTC, lord-haffi commented
Grundsätzlich (hatte @hf-kklein mal irgendwo festgehalten, weiß nicht wo): Alle technischen Kommentare (d.h. z.B. auch die docstrings für die Validatoren) bitte auf Englisch. Fachliche Docstrings, d.h. eigentlich alle docstrings, die Felder beschreiben, auf Deutsch.

2023-08-28 13:04 UTC, hf-ddernbach commented on src/bo4e/com/lastprofil.py
> +    """
e41bd3e74a8419edb5e385976f8bf173e71c7344

2024-01-15 08:58 UTC, lord-haffi commented on src/bo4e/bo/bilanzierung.py
> +    verbrauchsaufteilung: Optional[float] = None
Sicher, dass das hier nicht besser ein `Decimal` sein sollte? Wegen Gleitkommaungenauigkeiten und so...

2024-01-15 10:16 UTC, DeltaDaniel commented on src/bo4e/bo/bilanzierung.py
> +    verbrauchsaufteilung: Optional[float] = None
d77e02989fbfd0effcf6f471d6c9709f28fd1db5

2024-01-15 10:26 UTC, lord-haffi approved these changes
Ich hab jetzt nix mehr anzumerken bin fachlich jetzt aber auch nicht so in der Materie hier. @hf-kklein, @FreddyFox892 habt ihr noch was?

2024-04-29 17:47 UTC, lord-haffi commented
@hf-kklein, @DeltaDaniel, @FreddyFox892 ist das hier noch aktuell?

2024-04-29 21:16 UTC, hf-kklein commented
> ist das hier noch aktuell?

ja, annika und lev und franzi und joscha und ich könnten das gut gebrauchen

2024-04-30 07:11 UTC, lord-haffi requested changes
Falls der PR wieder aufgenommen wird: Die Änderungen sind nötig, damit alles schön miteinander funktioniert (inklusive Doku, JSON-Schemas, etc.). Bei den docstrings für die BOs und COMs musst du außerdem noch einen Verweis auf das JSON-Schema einbauen und das Diagramm einbinden. Da kannste dich problemlos an den anderen Docstrings orientieren,

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/bo/bilanzierung.py
> +    """
```suggestion
    """
    Prognosegrundlage.

    Besteht der Bedarf ein tagesparameteräbhängiges Lastprofil mit gemeinsamer Messung anzugeben,
    so ist dies über die 2 -malige Wiederholung des CAV Segments mit der Angabe der Codes E02 und E14 möglich.
    """
```

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/bo/bilanzierung.py
> +    """
```suggestion
    """
    Wahlrecht der Prognosegrundlage.

    true = Wahlrecht beim Lieferanten vorhanden
    """
```

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/bo/bilanzierung.py
> +    """
```suggestion
    """
    Grund Wahlrecht der Prognosegrundlage.

    true=Wahlrecht beim Lieferanten vorhanden
    """
```

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/com/lastprofil.py
> +    """
```suggestion
    einspeisung: Optional[bool] = None  #: Einspeiseprofil: True/False
```

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/com/tagesparameter.py
> +"""
```suggestion
"""
Contains tagesparameter class
"""
```

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/com/lastprofil.py
> +    """
Docstring anpassen

2024-04-30 07:11 UTC, lord-haffi commented on src/bo4e/bo/bilanzierung.py
> +    """
Docstring anpassen

2024-04-30 13:11 UTC, DeltaDaniel commented on src/bo4e/bo/bilanzierung.py
> +    """
a41916b3b3454ae513c70a1017f481711547856f

2024-09-11 13:34 UTC, lord-haffi reviewed
Hab noch mal an die Uppercase Thematik erinnern wollen. Ansonsten passt das für mich.

2024-09-11 13:34 UTC, lord-haffi commented on src/bo4e/enum/fallgruppenzuordnung.py
> +    """RLM ohne Tagesband"""
Hatte Freddy damals schon kommentiert, hier nochmal, weil der PR ja mittlerweile schon ein Fossil ist 🙈

2024-09-11 13:35 UTC, lord-haffi approved these changes

2025-03-20 11:02 UTC, hf-aschloegl commented on src/bo4e/enum/fallgruppenzuordnung.py
> +    """RLM ohne Tagesband"""
https://github.com/bo4e/BO4E-python/pull/508/commits/b7d336dcc812e9fedc3b70f8985298cdd236a3f8

2025-03-20 11:11 UTC, hf-aschloegl commented on src/bo4e/com/lastprofil.py
> +    einspeisung: Optional[bool] = None  #: Einspeiseprofil: True/False
```suggestion
    ist_einspeisung: Optional[bool] = None  #: Einspeiseprofil: True/False
```

2025-03-20 11:17 UTC, hf-fvesely commented on src/bo4e/bo/bilanzierung.py
> +    true = Wahlrecht beim Lieferanten vorhanden
achtung kein bool

2025-03-20 11:19 UTC, hf-fvesely commented on src/bo4e/enum/abwicklungsmodell.py
> +    Art der Abwicklungsmodell (E-Mob)
des Abwicklungsmodells

2025-03-20 11:24 UTC, hf-aschloegl commented on src/bo4e/bo/bilanzierung.py
> +    true=Wahlrecht beim Lieferanten vorhanden
https://github.com/bo4e/BO4E-python/pull/508/commits/83a567e304fe0d3d62be7af00d080bf6feeaf733

2025-03-20 11:24 UTC, hf-aschloegl commented on src/bo4e/enum/abwicklungsmodell.py
> +    Art der Abwicklungsmodell (E-Mob)
https://github.com/bo4e/BO4E-python/pull/508/commits/519db12f0a834d2abf6c50ab8e8fa1abf336404f

2025-03-20 11:26 UTC, hf-aschloegl commented on src/bo4e/enum/abwicklungsmodell.py
> +    MODEL_1 = "MODEL_1"  #: MODEL_1
https://github.com/bo4e/BO4E-python/pull/508/commits/c301307a96507768bbe9f1da617dcaee661788f0

2025-03-20 11:45 UTC, merged